### ISSUE TITLE
Update the feature list of `parity-scale-codec` dependency

### ISSUE THREAD

**Issue by rnbguy** [cosmos/ibc-rs#1124]
https://github.com/cosmos/ibc-rs/blob/5e7ff8e42c15592cff22a14536cc479f08cf8024/Cargo.toml#L107

`"full"` feature is deprecated and [doesn't enable anything](https://github.com/paritytech/parity-scale-codec/blob/a1c9b026a6d6a5ed7f1eebbf7aeb97177420abc6/Cargo.toml#L55). Rather this should be `"derive"`.

---

Although, there is an interesting scenario with `scale-info` dependency.

```rs
#[derive(parity_scale_codec::Encode, parity_scale_codec::Decode)]
pub struct Signer(String);
```

the above doesn't compile with
```toml
[dependencies]
parity-scale-codec = { version = "3.6.5", default-features = false }
```
or
```toml
[dependencies]
parity-scale-codec = { version = "3.6.5", default-features = false, features = ["full"] }
```
but with the following it compiles

```toml
[dependencies]
parity-scale-codec = { version = "3.6.5", default-features = false }
scale-info         = { version = "2.10.0", default-features = false }
```

of course it also compiles with
```toml
[dependencies]
parity-scale-codec = { version = "3.6.5", default-features = false, features = ["derive"] }
```

**Comment by seanchen1991** [comment]
You mention two possible options that successfully compile. Should we go with the first or the second?

**Comment by seanchen1991** [comment]
Actually, I see that you touched this code 3 weeks ago (though the `parity-scale-codec` dependency still has `features = [ "full" ]` enabled). Is this issue still relevant?

**Comment by rnbguy** [comment]
It is still relevant :slightly_smiling_face:  I modified those lines in `chore(deps)` PR. but I forgot to take care of this issue :sweat_smile:

**Comment by rnbguy** [comment]
> You mention two possible options that successfully compile. Should we go with the first or the second?

It should be something like this,

```toml
parity-scale-codec = { version = "3.6.5", default-features = false, features = [ "derive" ] }
scale-info         = { version = "2.10.0", default-features = false }
```
