### ISSUE TITLE
imp: feature gate `ibc` exports

### ISSUE THREAD

**Issue by rnbguy** [cosmos/ibc-rs#1138]
## Improvement Summary

The top `ibc` crate exports everything in the repo. This may not be intended, especially in the CosmWasm context. (See cosmos/rollkit-ibc#15). Currently, this can be avoided by importing the sub-crates directly. This may be a bit messy to maintain as a user has to maintain a consistent version across the sub-crates.

## Proposal

We can introduce features for each sub-crate:

```toml
[features]
core = ["dep:ibc-core"]
clients = ["dep:ibc-clients"]
primitives = ["deps:ibc-primitives"]
# ... for each sub-crate dependency
std = [
    "ibc-core?/std",
    "ibc-clients?/std",
    "ibc-primitives?/std",
]
serde = [
    "ibc-core?/serde",
    "ibc-clients?/serde",
    "ibc-primitives?/serde",
]
# ... for each feature
```

[cargo-doc](https://doc.rust-lang.org/cargo/reference/features.html) documents the usage of `"package-name?/feature-name"`.

With this, now we can 

```
ibc = { version = "0.50.0", features = ["core", "primitives", "serde"] }
```
Which is semantically equivalent to,

```
ibc-core = { version = "0.50.0", features = ["serde"] }
ibc-primitives = { version = "0.50.0", features = ["serde"] }
```
