### ISSUE TITLE
Add serialization and deserialization features for codec and borsh to the host type in ics24

### ISSUE THREAD

**Issue by DaviRain-Su** [cosmos/ibc-rs#259]
## Summary

```toml
## this for codec 
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.1.2", default-features = false, features = ["derive"] }
sp-runtime = {  version = "7.0.0", default-features = false }
## this for borsh
borsh = {version = "0.9.3", default-features = false }
```
example case ClientId: 
```rust
use serde::{Deserialize, Serialize};

use codec::{Decode, Encode};
use scale_info::TypeInfo;
use sp_runtime::RuntimeDebug;
use borsh::{BorshSerialize, BorshDeserialize};


#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub struct ClientId(pub String);

#[cfg(feature = "codec")]
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize, Encode, Decode, RuntimeDebug, TypeInfo)]
pub struct ClientId(pub String);

#[cfg(feature = "borsh")]
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize, BorshSerialize, BorshDeserialize)]
pub struct ClientId(pub String);
```

## Acceptance Criteria

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
